# Generated by Django 2.2 on 2019-04-18 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
    ]
