# Generated by Django 2.2 on 2019-05-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(max_length=300),
        ),
    ]
